### ISSUE TITLE
SOLIDの練習

### ISSUE THREAD

**Issue by hiroto1130** [hiroto1130/SOLID#1]
## 目的

SOLIDの原則を実装したcodeを書き、レビューしてもらう

## タスク

- [ ] SRP ( Single Responsibility Principle ) の実装(#2)
- [ ] OCP ( Open/closed principle ) の実装(#3)
- [ ] LSP ( Liskov substitution principle ) の実装(#4)
- [ ] ISP ( Interface segregation principle ) の実装(#5)
- [ ] DIP( Dependency inversion principle ) の実装(#6)
